/*
 * Weekly
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.weekly.api;

import org.weekly.invoker.ApiException;
import org.junit.Test;
import org.junit.Ignore;
import org.weekly.model.BasicObject;
import org.weekly.model.Task;

import java.util.List;

/**
 * API tests for TasksApi
 */
@Ignore
public class TasksApiTest {

    private final TasksApi api = new TasksApi();

    
    /**
     * Create tasks.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTasksTest() throws ApiException {
        Integer weekNo = null;
        Integer weekYear = null;
        List<Task> task = null;
        List<Task> response = api.createTasks(weekNo, weekYear, task);

        // TODO: test validations
    }
    
    /**
     * Decrement a task priority.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void decrementTaskPriorityTest() throws ApiException {
        String id = null;
        Task response = api.decrementTaskPriority(id);

        // TODO: test validations
    }
    
    /**
     * Delete a task.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTasksTest() throws ApiException {
        List<String> ERROR_UNKNOWN = null;
        api.deleteTasks(ERROR_UNKNOWN);

        // TODO: test validations
    }
    
    /**
     * Get task.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIndividualTaskTest() throws ApiException {
        String id = null;
        Task response = api.getIndividualTask(id);

        // TODO: test validations
    }
    
    /**
     * Get tasks for a week.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTasksTest() throws ApiException {
        Integer weekNo = null;
        Integer weekYear = null;
        List<Task> response = api.getTasks(weekNo, weekYear);

        // TODO: test validations
    }
    
    /**
     * Increment a task priority.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void incrementTaskPriorityTest() throws ApiException {
        String id = null;
        Task response = api.incrementTaskPriority(id);

        // TODO: test validations
    }
    
    /**
     * Update a task.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskByIdTest() throws ApiException {
        String id = null;
        Task body = null;
        Task response = api.updateTaskById(id, body);

        // TODO: test validations
    }
    
    /**
     * Update a task label.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskLabelTest() throws ApiException {
        String id = null;
        String label = null;
        Task response = api.updateTaskLabel(id, label);

        // TODO: test validations
    }
    
    /**
     * Update a task state.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskStateTest() throws ApiException {
        String id = null;
        String state = null;
        Task response = api.updateTaskState(id, state);

        // TODO: test validations
    }
    
    /**
     * Update a tasks.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTasksTest() throws ApiException {
        List<Task> task = null;
        List<Task> response = api.updateTasks(task);

        // TODO: test validations
    }
    
}
