/*
 * Weekly
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.weekly.api;

import org.weekly.invoker.ApiException;
import org.junit.Test;
import org.junit.Ignore;
import org.weekly.model.TaskLabel;

/**
 * API tests for TaskLabelsApi
 */
@Ignore
public class TaskLabelsApiTest {

    private final TaskLabelsApi api = new TaskLabelsApi();

    
    /**
     * Get all task labels.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskLabelsTest() throws ApiException {
        TaskLabel response = api.getTaskLabels();

        // TODO: test validations
    }
    
}
