package org.weekly.api.impl;

import org.weekly.api.*;
import org.weekly.model.Week;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;

import org.apache.cxf.jaxrs.ext.multipart.*;

import io.swagger.annotations.Api;

/**
 * PlanIt
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */
public class CalendarApiServiceImpl implements CalendarApi {
    /**
     * Get current week based on a timezone
     *
     */
    public Week getCurrentWeek() {
        // TODO: Implement...
        
        return null;
    }
    
}

