///**
// * Weekly
// * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
// *
// * OpenAPI spec version: 1.0.0
// *
// *
// * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
// * https://openapi-generator.tech
// * Do not edit the class manually.
// *
// * Licensed under the Apache License, Version 2.0 (the "License");
// * you may not use this file except in compliance with the License.
// * You may obtain a copy of the License at
// *
// * http://www.apache.org/licenses/LICENSE-2.0
// *
// * Unless required by applicable law or agreed to in writing, software
// * distributed under the License is distributed on an "AS IS" BASIS,
// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// * See the License for the specific language governing permissions and
// * limitations under the License.
// */
//
//
//package org.weekly.api;
//
//import org.junit.Test;
//import org.junit.runner.RunWith;
//import org.springframework.boot.test.context.SpringBootTest;
//import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
//import org.springframework.test.context.web.WebAppConfiguration;
//
//
//
///**
// * Weekly
// *
// * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
// *
// * API tests for TaskApi
// */
//@RunWith(SpringJUnit4ClassRunner.class)
//@WebAppConfiguration
//@SpringBootTest
//public class TaskApiTest {
//
//
//    /**
//     * Create a task.
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void createTaskTest() {
//        Integer weekNo = null;
//        Integer weekYear = null;
//        //Task response = api.createTask(weekNo, weekYear);
//        //assertNotNull(response);
//        // TODO: test validations
//
//
//    }
//
//}
