/*
 * Weekly
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.weekly.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BasicObject
 */
public class BasicObjectTest {
    private final BasicObject model = new BasicObject();

    /**
     * Model tests for BasicObject
     */
    @Test
    public void testBasicObject() {
        // TODO: test BasicObject
    }

    /**
     * Test the property 'updateTs'
     */
    @Test
    public void updateTsTest() {
        // TODO: test updateTs
    }

    /**
     * Test the property 'creationTs'
     */
    @Test
    public void creationTsTest() {
        // TODO: test creationTs
    }

}
