/*
 * Weekly
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.weekly.model;

import org.junit.Test;


/**
 * Model tests for TaskAllOf
 */
public class TaskAllOfTest {
    private final TaskAllOf model = new TaskAllOf();

    /**
     * Model tests for TaskAllOf
     */
    @Test
    public void testTaskAllOf() {
        // TODO: test TaskAllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'contents'
     */
    @Test
    public void contentsTest() {
        // TODO: test contents
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'weekYear'
     */
    @Test
    public void weekYearTest() {
        // TODO: test weekYear
    }

    /**
     * Test the property 'weekNo'
     */
    @Test
    public void weekNoTest() {
        // TODO: test weekNo
    }

}
