/*
 * Weekly
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.weekly.model;

import org.junit.Test;


/**
 * Model tests for UserAllOf
 */
public class UserAllOfTest {
    private final UserAllOf model = new UserAllOf();

    /**
     * Model tests for UserAllOf
     */
    @Test
    public void testUserAllOf() {
        // TODO: test UserAllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'picture'
     */
    @Test
    public void pictureTest() {
        // TODO: test picture
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'priorities'
     */
    @Test
    public void prioritiesTest() {
        // TODO: test priorities
    }

    /**
     * Test the property 'states'
     */
    @Test
    public void statesTest() {
        // TODO: test states
    }

    /**
     * Test the property 'preferences'
     */
    @Test
    public void preferencesTest() {
        // TODO: test preferences
    }

}
