/*
 * Weekly
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.weekly.model;

import org.junit.Test;


/**
 * Model tests for Week
 */
public class WeekTest {
    private final Week model = new Week();

    /**
     * Model tests for Week
     */
    @Test
    public void testWeek() {
        // TODO: test Week
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'weekNo'
     */
    @Test
    public void weekNoTest() {
        // TODO: test weekNo
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

}
