CREATE TABLE USERS(
    ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(128),
    LAST_NAME VARCHAR(128),
    EMAIL VARCHAR(256));

CREATE TABLE TASKS(
    ID INT,
    WEEK_NO INT,
    WEEK_YEAR INT,
    USER_ID INT,
    SUMMARY VARCHAR(128),
    CONTENTS CLOB,r
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    PRIMARY KEY(ID,WEEK_NO,WEEK_YEAR,USER_ID));

CREATE INDEX WEEK_IDX ON TASKS(WEEK_NO,WEEK_YEAR);

CREATE INDEX WEEK_USER_IDX ON TASKS(WEEK_NO,WEEK_YEAR,USER_ID);